# The URL the site will be built for
base_url = "https://outurnate.com"
title = "Joe Dillon"
description = "I tend to end up writing more code than words about code, but I'm trying to change that"
default_language = "en"
theme = "default"
compile_sass = true
minify_html = true
build_search_index = false
generate_feed = true
feed_filename = "atom.xml"

[markdown]
highlight_code = true

[extra]