shape: sequence_diagram
Client;
ISCV Server;
"Part A: Request body contains values of wa, wtrealm, wctx, and wct - this request simply converts\nthem to query parameters": {
    Client->ISCV Server: POST /STS/Forms/Login.aspx;
    ISCV Server->Client: 302 FOUND /STS/Windows/WinLogin.aspx?wa=...&wt=...&wtrealm=...&wctx=...&wct=...;
}
"Part B: WWW-Authenticate challenge/response request is turned into a AuthContext token, which\nwill be redeemed in the next part": {
    Client->ISCV Server: GET /STS/Windows/WinLogin.aspx?wa=...&wt=...&wtrealm=...&wctx=...&wct=...;
    ISCV Server->Client: 401 UNAUTHORIZED;
    Client->ISCV Server: GET /STS/Windows/WinLogin.aspx?wa=...&wt=...&wtrealm=...&wctx=...&wct=...;
    ISCV Server->Client: 302 FOUND /STS/Forms/Login.aspx?AuthContext=...&wa=...&wt=...&wtrealm=...&wctx=...&wct=...;
}
"Part C: The client redeems the AuthContext": {
    Client->ISCV Server: GET /STS/Forms/Login.aspx?AuthContext=...&wa=...&wt=...&wtrealm=...&wctx=...&wct=...;
    ISCV Server->Client: 302 FOUND /STS/Forms/default.aspx?wa=...&wt=...&wtrealm=...&wctx=...&wct=...;
}
end: The remainder of the authentication chain will be omitted, as it is irrelevant. {
    shape: text
    near: bottom-center
}