vars: {
  d2-config: {
    dark-theme-overrides: {
      N1: "#D6D6D6"
      N2: "#C2C2C2"
      N3: "#ADADAD"
      N4: "#5B5B5B"
      N5: "#474747"
      N6: "#323232"
      N7: "#000000"

      B1: "#98E585" # --diagram-color-a
      B2: "#6B946C" # --bordercolor
      B3: "#389844" # --highlight-fill
      B4: "#0C200D" # --diagram-color-b
      B5: "#0C200D" # --diagram-color-b
      B6: "#0C200D" # --diagram-color-b

      AA4: "#389844" # --highlight-fill
      AA5: "#389844" # --highlight-fill

      AB4: "#6B946C" # --bordercolor
      AB5: "#389844" # --highlight-fill
    }
    theme-overrides: {
      N1: "#0F0F25"
      N2: "#6C6C6C"
      N3: "#999999"
      N4: "#D2D2D2"
      N5: "#E1E1E1"
      N6: "#F1F1F1"
      N7: "#DDDDDD"

      B1: "#0C200D" # --diagram-color-a
      B2: "#6B946C" # --bordercolor
      B3: "#389844" # --highlight-fill
      B4: "#98E585" # --diagram-color-b
      B5: "#98E585" # --diagram-color-b
      B6: "#98E585" # --diagram-color-b

      AA4: "#389844" # --highlight-fill
      AA5: "#389844" # --highlight-fill

      AB4: "#6B946C" # --bordercolor
      AB5: "#389844" # --highlight-fill
    }
  }
}
